baseURL = 'https://climbonparks.ca/'
languageCode = 'en-ca'
title = "Climb In Parks"
theme = "freelancer"

[params]
  tagLine = "Allow climbing in Ontario Parks!"

  homePosts = 3
  homeProjects = 3

  aboutLeft = "The Ontario Alliance of Climbers (OAC) is a volunteer non-profit organization that works in collaboration with stakeholders to steward access to outdoor rock climbing."
  aboutRight = "The #SaveClimbingAtDG campaign is an OAC initiative advocating for climbing on our public lands. For more details about climbing in Ontario, see our website below."

[params.sbform]
      token = ""

[params.homebutton]
  text = "Ontario Alliance of Climbers"
  link = "https://ontarioallianceofclimbers.ca"
  icon = "fa-house"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
